[package]
name = "nupi-desktop"
version = "0.1.0"
description = "Nupi desktop app"
authors = ["nupi.ai"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }
tonic-build = "0.12"

[dependencies]
tauri = { version = "2", features = [ "tray-icon", "image-png"] }
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.31", features = ["bundled"] }
dirs = "5"
url = "2"
hound = "3.5"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "fs", "io-util"] }
tokio-stream = { version = "0.1", features = ["sync"] }
once_cell = "1"
tonic = { version = "0.12", features = ["channel", "transport", "tls"] }
prost = "0.13"
prost-types = "0.13"
